Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__main__.py", line 11, in <module>
    esptool._main()
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 1031, in _main
    main()
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 671, in main
    esp = esp or get_default_connected_device(
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 919, in get_default_connected_device
    _esp = chip_class(each_port, initial_baud, trace)
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/loader.py", line 280, in __init__
    self._port = serial.serial_for_url(port)
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py", line 336, in open
    self._update_dtr_state()
  File "/home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py", line 713, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:63 (message):
  
  /home/minhnhat/.espressif/python_env/idf5.1_py3.8_env/bin/python;;/home/minhnhat/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



